### ISSUE TITLE
NodeConf Brazil

### ISSUE THREAD

**Issue by jeanlucaslima** [nodeconf/collective#13]
Hello! Announcing NodeConf Brazil. 

Date: 4th and 5th of July - 2016
Local: São Paulo - Brazil - Teatro Frei Caneca [map](https://www.google.com.br/maps/place/Parada+Frei+Caneca/@-23.5539247,-46.6550992,17z/data=!4m2!3m1!1s0x94ce59cdadab0b21:0x7ce254dabcac8016)

Would like to have the address brazil.nodeconf.com - is it possible?

**Comment by jeanlucaslima** [comment]
According to issue #5: 
- [x] Must adopt a Code of Conduct.
- [x] Must be "community oriented."
- [x] If selling sponsorships a 10% discount must be offered to Corporate Members of the Node Foundation. However, the collective will send your sponsorship materials to the events contact at each company at your request.
- [x] If selling tickets a 10% discount must be offered to Individual Members of the Node Foundation. However, the collective will send information about your event to the entire membership at your request.
- [x] If there is a "vendor area" or "swag area" the Node Foundation should be extended, without charge, the option of using those areas with the same treatment as your lowest sponsorship level that includes those considerations. In practice this will be rare as the foundation has limited resources in sending representatives to events.

On the last topic, the Foundation is invited to do so.

**Comment by mikeal** [comment]
We don't actually need those foundation benefits :)

**Comment by mikeal** [comment]
Created a brazil repo and team and invited you to the team :)

**Comment by thebergamo** [comment]
Thanks @mikeal :)

**Comment by thebergamo** [comment]
@mikeal can you add me to brazil repo?

**Comment by jeanlucaslima** [comment]
@mikeal please add @thebergamo as well :) he's running this with me too.

**Comment by mikeal** [comment]
Added @thebergamo and made @jeanleonino a team maintainer for Brazil :)

**Comment by thebergamo** [comment]
thanks very much @mikeal :)

**Comment by iancrowther** [comment]
omg!! I love Brazil!! Good luck with the event

https://twitter.com/iancrowther/status/717831965001560064

**Comment by thebergamo** [comment]
Thanks @iancrowther we'll be much glad with your presence on the event :)

**Comment by thebergamo** [comment]
Well, probably this issue can be closed now!

Our conf are ended!

![NodeConfBrazil2016](https://cdn-images-1.medium.com/max/2000/1*xOhA-15eAOVXuc9XGUsbhQ.jpeg)

**Comment by thebergamo** [comment]
This issue can be closed @mikeal

**Comment by mikeal** [comment]
Looks great!
