### ISSUE TITLE
NodeConf Argentina

### ISSUE THREAD

**Issue by a0viedo** [nodeconf/collective#14]
Hi @mikeal! Previously we talked about Buenos Aires' ONE-SHOT. Now we've launched the site for [NodeConf Argentina](https://nodeconf.com.ar/) and was wondering if we could use a repository to redirect http://argentina.nodeconf.com to the site.

The group of organizers are: @bevacqua @jaclar @pr0duc3r and me.

**Comment by bevacqua** [comment]
Note: Please have it redirect to `nodeconf.com.ar`, as the apex redirects to `some_year.nodeconf.com.ar`

**Comment by jeanlucaslima** [comment]
Uhu! You too doing a NodeConf! I'm doing [NodeConf Brazil](http://brazil.nodeconf.com/) would love to visit you (when will it be?) and help any way possible.

**Comment by bevacqua** [comment]
[2016.nodeconf.com.ar](https://2016.nodeconf.com.ar)

**Comment by jeanlucaslima** [comment]
Thanks, @bevacqua, the website is pretty neat :)

**Comment by jeanlucaslima** [comment]
Hey @bevacqua, [your article](https://ponyfoo.com/articles/nodeconf-hits-the-ground-running-in-latin-america) here says it's the first NodeConf in Latin America, and it is literally after NodeConf Brazil. It's kinda of a problem as NodeConf organizer because we are looking for sponsors saying exactly that.

**Comment by bevacqua** [comment]
Oh crap. I wrote that a long time ago and just copied and pasted. Fixing.

**Comment by jeanlucaslima** [comment]
@bevacqua it's ok! Haha, and thanks for answering so fast :)

**Comment by bevacqua** [comment]
Fixed

**Comment by a0viedo** [comment]
http://argentina.nodeconf.com is live!

**Comment by bevacqua** [comment]
:tada:
