### ISSUE TITLE
NodeConf Armenia

### ISSUE THREAD

**Issue by nairihar** [nodeconf/collective#20]
Hi @mikeal!
Thanks for sending us the guide on how to run a NodeConf.

So it'll be a free one-day event in Armenia 🇦🇲 in the first half of 2020. As Armenia is not a big country, and we also plan to organize the conference, not in the capital we would like to keep Armenia instead of the city name.

That would be also great to have the address armenia.nodeconf.com

We've already organized a few events on both Javascript and Node.js (conferences and meetups) in Armenia. Check the following links for more details:

https://github.com/NodeJSArmenia
https://github.com/JSConfArmenia

cc: @tovmassian @modularcoder

**Comment by mikeal** [comment]
> So it'll be a free one-day event in Armenia 🇦🇲 in the first half of 2020. As Armenia is not a big country, and we also plan to organize the conference, not in the capital we would like to keep Armenia instead of the city name.

Sounds good to me. This rule is primarily there for larger countries.

**Comment by nairihar** [comment]
Hi there, I'm back with great news :) 

@mikeal We are planning to organize NodeConf Armenia 2020

More info here: https://nodeconf.am/

Could you please provide us: "armenia.nodeconf.com" domain?

**Comment by mikeal** [comment]
@nairihar I setup a CNAME pointed at `nodeconf.am`, it should work after it propogates.

**Comment by nairihar** [comment]
Thanks a lot!

**Comment by nairihar** [comment]
@mikeal Seems there is a DNS problem

<img width="1601" alt="Screen Shot 2020-02-19 at 1 37 20 AM" src="https://user-images.githubusercontent.com/15065065/74780122-62024f00-52b8-11ea-9c07-aacb65e2305c.png">

**Comment by mikeal** [comment]
That’s not a DNS error, that’s a Cloudflare configuration error that looks to be on your side.

If you ping the domains for nodeconf.am and armenia.nodeconf.com you get the same IP address.

**Comment by nairihar** [comment]
@mikeal to be able to fix this problem we need action from your side.

Could you add these nameservers in your side:
ines.ns.cloudflare.com
oswald.ns.cloudflare.com

<img width="736" alt="Screen Shot 2020-02-20 at 1 01 46 AM" src="https://user-images.githubusercontent.com/15065065/74875989-99d2ca80-537c-11ea-89a5-3a92e4161ca2.png">

**Comment by nairihar** [comment]
@mikeal thanks for the note, I've contacted with our technical team, we have some problems regarding the Cloudflare part. Could you just redirect to "nodeconf.am" instead of pointing the same IP address, also for SEO, that would be better?

**Comment by mikeal** [comment]
I don’t have a server setup for the primary domain right now so I don’t have an easy way to setup an HTTP forward :(

**Comment by tovmassian** [comment]
@mikeal we moved from CloudFlare to AWS and now https://armenia.nodeconf.com works! Thanks a lot for your support^^
