### ISSUE TITLE
NodeConf Barcelona

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeconf/collective#7]
Hola!

NodeConf Barcelona is coming up on Nov 21, just after DockerCon Barcelona. We have the website, 10/12 speakers (2 tba), venue, catering etc. all set up. We could use a little PR to get the word out and there are some sponsorship opportunities left.

@mikeal Any suggestions / ideas?

If there's someone from the NodeConf collective or the Foundation, we'd provide discount codes of course.

**Comment by mikeal** [comment]
Give me some tweets you want to send out and I can post them or even queue them up to go out over the course of a few weeks from the @nodeconf account. I can also ping foundation people about retweeting one of them from the @nodejs account.

**Comment by iancrowther** [comment]
Happy to do some PR at LNUG if you have some links/tweets..

**Comment by PatrickHeneise** [comment]
@mikeal, @iancrowther here are some of the tweets sent:

NodeConfBcn: NodeConf Barcelona, Novemer 21. 1 day, 12 speakers. Talks and workshop, all about #nodejs https://t.co/vAuGg2yZIS

NodeConfBcn: Summer is over - Nodevember is coming! #NodeConf is coming to Barcelona with 12 great speakers! Check out http://barcelona.nodeconf.com #nodejs 

NodeConfBcn: Running a @nodejs user group? Reply to get a discount code for #NodeConfBcn! #community #jslove

YLDio: Don't miss out on our @nodejs workshop following @NodeConfBcn! Tickets have just gone on sale, get yours:  http://t.co/DOmqN3sP4b #nodejs

NodeConfBcn: What better way to spend a Sunday together with other @nodejs engineers, have coffee and do a Performance Training? http://t.co/d09DsNGeC0
